# -*- coding: utf-8 -*-
"""Project .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/139GgqTi-1rl2zGoJifoTYkp-N0J7RGZt
"""

!pip install tensorflow opencv-python matplotlib

import cv2

import numpy as np

import matplotlib.pyplot as plt

img = cv2.imread('photo2.jpg')

edges=cv2.Canny(img,100,200)

plt.subplot(121),plt.imshow(img,cmap = 'gray')
plt.title('Original Image'), plt.xticks([]), plt.yticks([])
plt.subplot(122),plt.imshow(edges,cmap = 'gray')
plt.title('Edge Image'), plt.xticks([]), plt.yticks([])
plt.show(),